name:                haskell-lenses
version:             0.1.0.0
github:              "githubuser/haskell-lenses"
license:             BSD3
author:              "Lorenzo Lopez"
maintainer:          "lorenzo.lopez@intec.es"
copyright:           "2019 Lorenzo Lopez"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/batou99/haskell-lenses#readme>

dependencies:
- base >= 4.7 && < 5
- lens
- containers

library:
  source-dirs: src

executables:
  haskell-lenses-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-lenses

tests:
  haskell-lenses-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-lenses
